spring:
  profiles:
    active: dev

  application:
    name: product-service

  eureka:
    client:
      serviceUrl:
        defaultZone=http://localhost:8761/eureka:

server.port: 8086
## server.port: 8080