spring:
  profiles:
    active: dev

  application:
    name: inventory-service

  eureka:
    client:
      serviceUrl:
        defaultZone=http://localhost:8761/eureka:

server.port: 0 # It means it will run on any free port
#server.port: 8082
